// Listing 13-10: parse_machfile

load_return_t parse_machfile(
    struct vnode       *vp,     // vnode pointer from imgp
    vm_map_t            map,    // map, as initialized by load_machfile
    thread_t            thread, // thread, from load_machfile
    struct mach_header *header, // header, from load_machfile
    off_t               file_offset, // Architecture offset 
    off_t               macho_size,  // Architecture binary size
    int                 depth, // recursion level. Started at 0.
    int64_t             aslr_offset, // generated by load_..
    load_result_t       *result);